###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: admin-mysql
      working_dir: /application
      volumes:
        - ./dadosMysql:/var/lib/mysql:rw
      environment:
        - MYSQL_ROOT_PASSWORD=livre
        - MYSQL_DATABASE=admin
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "7002:3306"

    webserver:
      image: nginx:alpine
      container_name: admin-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: admin-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

